services:
  parser:
    image: docker.xuanyuan.me/wujunwei928/parse-video:latest
    container_name: video-parser
    restart: always
    ports:
      - "4080:4080"
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      - bridge_net

  webui:
    image: ghcr.nju.edu.cn/zuoa/parse-video-webui:main
    container_name: video-parse-webui
    restart: always
    ports:
      - "9020:9020"
    environment:
      - "TZ=Asia/Shanghai"
      - "PARSER_URL=http://parser:4080"
    depends_on:
      - parser
    networks:
      - bridge_net

networks:
  bridge_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 